<?php
// module/Album/view/album/album/index.phtml:

$title = 'My workpackages';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('workpackage', array('action'=>'add'));?>">Add new packages</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($projectparts as $workpackage) : ?>
<tr>
    <td><?php echo $this->escapeHtml($workpackage->name);?></td>
    <td><?php echo $this->escapeHtml($workpackage->description);?></td>
    <td>
        <a href="<?php echo $this->url('workpackage',
            array('action'=>'edit', 'id' => $workpackage->id));?>">Edit</a>
        <a href="<?php echo $this->url('workpackage',
            array('action'=>'delete', 'id' => $workpackage->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>