<?php
// module/Album/view/album/album/edit.phtml:

$title = $this->escapeHtml($project->name);
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'project',
    array(
        'action' => 'index',
        'id'     => $this->id
    )
));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
//echo var_dump($project);
?>
<a href="<?php echo $this->url('project',
            array('action'=>'add', 'id' => $this->id));?>">add Project</a>
<hr>
<p style="font-size: 1.5em"><?php echo "Description"; ?></p>
<?php echo $this->escapeHtml($project->description); ?>
<br />
<br />
<p style="font-size: 1.3em"><?php echo "Start date"; ?></p>
<?php echo $this->formdate($form->get('startdate')); ?>
<p style="font-size: 1.3em"><?php echo "End date"; ?></p>
<?php echo $this->formdate($form->get('enddate')); ?>
<br />
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>